services:
  your_service_name:
    build:
      context: .
      dockerfile: nlp_content_validity/visualization/Dockerfile
    ports:
      - "8002:8002"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1